# name               lanes                                alias            speed        index    mtu      fec
Ethernet1            21,16,23,19                          Port1            100000       0       9126    rs 
Ethernet2            22,18,20,17                          Port2            100000       1       9126    rs 
Ethernet3            29,25,26,24                          Port3            100000       2       9126    rs 
Ethernet4            31,30,27,28                          Port4            100000       3       9126    rs 
Ethernet5            36,33,37,34                          Port5            100000       4       9126    rs 
Ethernet6            38,35,39,32                          Port6            100000       5       9126    rs 
Ethernet7            44,40,43,42                          Port7            100000       6       9126    rs 
Ethernet8            45,46,47,41                          Port8            100000       7       9126    rs 
Ethernet9            50,49,51,48                          Port9            100000       8       9126    rs 
Ethernet10           54,53,55,52                          Port10           100000       9       9126    rs 
Ethernet11           58,57,61,59                          Port11           100000       10      9126    rs 
Ethernet12           62,63,60,56                          Port12           100000       11      9126    rs 
Ethernet13_1         69,65,71,67                          Port13_1         100000       24      9126    rs 
Ethernet13_2         68,64,70,66                          Port13_2         100000       24      9126    rs 
Ethernet14_1         7,0,5,3                              Port14_1         100000       25      9126    rs 
Ethernet14_2         6,2,4,1                              Port14_2         100000       25      9126    rs 
Ethernet15_1         74,72,73,77                          Port15_1         100000       26      9126    rs 
Ethernet15_2         75,76,78,79                          Port15_2         100000       26      9126    rs 
Ethernet16_1         13,14,10,9                           Port16_1         100000       27      9126    rs 
Ethernet16_2         15,12,8,11                           Port16_2         100000       27      9126    rs 
Ethernet17_1         83,84,86,89                          Port17_1         100000       28      9126    rs 
Ethernet17_2         85,82,88,87                          Port17_2         100000       28      9126    rs 
Ethernet18_1         151,152,148,147                      Port18_1         100000       29      9126    rs 
Ethernet18_2         146,150,153,149                      Port18_2         100000       29      9126    rs 
Ethernet19_1         91,94,93,96                          Port19_1         100000       30      9126    rs 
Ethernet19_2         90,95,92,97                          Port19_2         100000       30      9126    rs 
Ethernet20_1         155,161,156,154                      Port20_1         100000       31      9126    rs 
Ethernet20_2         159,158,157,160                      Port20_2         100000       31      9126    rs 
Ethernet21           99,98,101,105                        Port21           100000       12      9126    rs 
Ethernet22           103,104,100,102                      Port22           100000       13      9126    rs 
Ethernet23           107,108,106,109                      Port23           100000       14      9126    rs 
Ethernet24           111,112,110,113                      Port24           100000       15      9126    rs 
Ethernet25           116,115,114,119                      Port25           100000       16      9126    rs 
Ethernet26           118,121,117,120                      Port26           100000       17      9126    rs 
Ethernet27           123,125,122,129                      Port27           100000       18      9126    rs 
Ethernet28           126,128,124,127                      Port28           100000       19      9126    rs 
Ethernet29           130,131,134,133                      Port29           100000       20      9126    rs 
Ethernet30           132,136,135,137                      Port30           100000       21      9126    rs 
Ethernet31           139,143,141,142                      Port31           100000       22      9126    rs 
Ethernet32           140,145,138,144                      Port32           100000       23      9126    rs 
