# enable platform-service
depmod -a

if [ "$(systemctl is-enabled pddf-platform-init.service 2>/dev/null)" = "masked" ]; then
    systemctl unmask pddf-platform-init.service > /dev/null 2>&1
fi
systemctl enable pddf-platform-init.service
systemctl start pddf-platform-init.service

if [ "$(systemctl is-enabled pddf-s3ip-init.service 2>/dev/null)" = "masked" ]; then
    systemctl unmask pddf-s3ip-init.service > /dev/null 2>&1
fi
systemctl enable pddf-s3ip-init.service
systemctl start pddf-s3ip-init.service

if [ "$(systemctl is-enabled watchdog.service 2>/dev/null)" = "masked" ]; then
    systemctl unmask watchdog.service > /dev/null 2>&1
fi
systemctl enable watchdog.service
systemctl start watchdog.service

if [ "$(systemctl is-enabled flines-common-platform-init.service 2>/dev/null)" = "masked" ]; then
    systemctl unmask flines-common-platform-init.service > /dev/null 2>&1
fi
systemctl enable flines-common-platform-init.service
systemctl start flines-common-platform-init.service

if [ "$(systemctl is-enabled fan-control.service 2>/dev/null)" = "masked" ]; then
    systemctl unmask fan-control.service > /dev/null 2>&1
fi
systemctl enable fan-control.service
systemctl start fan-control.service