# name               lanes                                alias            speed        index    mtu      fec
Ethernet0            2                                    Ethernet0        25000        0       9126    rs 
Ethernet1            1                                    Ethernet1        25000        1       9126    rs 
Ethernet2            0                                    Ethernet2        25000        2       9126    rs 
Ethernet3            3                                    Ethernet3        25000        3       9126    rs 
Ethernet4            6                                    Ethernet4        25000        4       9126    rs 
Ethernet5            4                                    Ethernet5        25000        5       9126    rs 
Ethernet6            7                                    Ethernet6        25000        6       9126    rs 
Ethernet7            5                                    Ethernet7        25000        7       9126    rs 
Ethernet8            8                                    Ethernet8        25000        8       9126    rs 
Ethernet9            10                                   Ethernet9        25000        9       9126    rs 
Ethernet10           11                                   Ethernet10       25000        10      9126    rs 
Ethernet11           9                                    Ethernet11       25000        11      9126    rs 
Ethernet12           14                                   Ethernet12       25000        12      9126    rs 
Ethernet13           12                                   Ethernet13       25000        13      9126    rs 
Ethernet14           15                                   Ethernet14       25000        14      9126    rs 
Ethernet15           13                                   Ethernet15       25000        15      9126    rs 
Ethernet16           16                                   Ethernet16       25000        16      9126    rs 
Ethernet17           17                                   Ethernet17       25000        17      9126    rs 
Ethernet18           18                                   Ethernet18       25000        18      9126    rs 
Ethernet19           19                                   Ethernet19       25000        19      9126    rs 
Ethernet20           20                                   Ethernet20       25000        20      9126    rs 
Ethernet21           21                                   Ethernet21       25000        21      9126    rs 
Ethernet22           22                                   Ethernet22       25000        22      9126    rs 
Ethernet23           23                                   Ethernet23       25000        23      9126    rs 
Ethernet24           25                                   Ethernet24       25000        24      9126    rs 
Ethernet25           24                                   Ethernet25       25000        25      9126    rs 
Ethernet26           26                                   Ethernet26       25000        26      9126    rs 
Ethernet27           28                                   Ethernet27       25000        27      9126    rs 
Ethernet28           27                                   Ethernet28       25000        28      9126    rs 
Ethernet29           30                                   Ethernet29       25000        29      9126    rs 
Ethernet30           29                                   Ethernet30       25000        30      9126    rs 
Ethernet31           32                                   Ethernet31       25000        31      9126    rs 
Ethernet32           31                                   Ethernet32       25000        32      9126    rs 
Ethernet33           34                                   Ethernet33       25000        33      9126    rs 
Ethernet34           33                                   Ethernet34       25000        34      9126    rs 
Ethernet35           36                                   Ethernet35       25000        35      9126    rs 
Ethernet36           35                                   Ethernet36       25000        36      9126    rs 
Ethernet37           38                                   Ethernet37       25000        37      9126    rs 
Ethernet38           37                                   Ethernet38       25000        38      9126    rs 
Ethernet39           39                                   Ethernet39       25000        39      9126    rs 
Ethernet40           40                                   Ethernet40       25000        40      9126    rs 
Ethernet41           42                                   Ethernet41       25000        41      9126    rs 
Ethernet42           41                                   Ethernet42       25000        42      9126    rs 
Ethernet43           44                                   Ethernet43       25000        43      9126    rs 
Ethernet44           43                                   Ethernet44       25000        44      9126    rs 
Ethernet45           46                                   Ethernet45       25000        45      9126    rs 
Ethernet46           45                                   Ethernet46       25000        46      9126    rs 
Ethernet47           47                                   Ethernet47       25000        47      9126    rs 
Ethernet48           55,53,54,52                          Ethernet48       100000       48      9126    rs 
Ethernet52           51,48,49,50                          Ethernet52       100000       49      9126    rs 
Ethernet56           62,61,63,60                          Ethernet56       100000       50      9126    rs 
Ethernet60           57,58,56,59                          Ethernet60       100000       51      9126    rs 
Ethernet64           69,68,71,70                          Ethernet64       100000       52      9126    rs 
Ethernet68           66,67,64,65                          Ethernet68       100000       53      9126    rs 
Ethernet72           76,78,79,77                          Ethernet72       100000       54      9126    rs 
Ethernet76           75,72,73,74                          Ethernet76       100000       55      9126    rs 
