# sonic clounix one image installer

SONIC_ONE_IMAGE = sonic-clounix.bin
$(SONIC_ONE_IMAGE)_MACHINE = clounix
$(SONIC_ONE_IMAGE)_IMAGE_TYPE = onie
$(SONIC_ONE_IMAGE)_INSTALLS += $(CLOUNIX_MODULE) $(CLX_UTILS)
$(SONIC_ONE_IMAGE)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_ONE_IMAGE)_INSTALLS += $(PDDF_PLATFORM_MODULE)

ifeq ($(CONFIGURED_ARCH), amd64)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(CLOUNIX_CLX12800_48D8E_PLATFORM_MODULE)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(CLOUNIX_CLX25600_48D8E_PLATFORM_MODULE)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(CLOUNIX_CLX2000_48Y8C_PLATFORM_MODULE)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(FLINES_DS410G_PLATFORM_MODULE)
else ifeq ($(CONFIGURED_ARCH),arm64)
$(SONIC_ONE_IMAGE)_LAZY_INSTALLS += $(FLINES_DS410H_PLATFORM_MODULE)
else
endif

ifeq ($(INSTALL_DEBUG_TOOLS),y)
$(SONIC_ONE_IMAGE)_DOCKERS += $(SONIC_INSTALL_DOCKER_DBG_IMAGES)
$(SONIC_ONE_IMAGE)_DOCKERS += $(filter-out $(patsubst %-$(DBG_IMAGE_MARK).gz,%.gz, $(SONIC_INSTALL_DOCKER_DBG_IMAGES)), $(SONIC_INSTALL_DOCKER_IMAGES))
else
$(SONIC_ONE_IMAGE)_DOCKERS = $(SONIC_INSTALL_DOCKER_IMAGES)
endif
SONIC_INSTALLERS += $(SONIC_ONE_IMAGE)
