# Pegatron Platform modules
FLINES_PLATFORM_MODULE_VERSION = 1.0.0
export FLINES_PLATFORM_MODULE_VERSION

ifeq ($(CONFIGURED_ARCH),amd64)
    TARGET_ARCH := x86_64
else ifeq ($(CONFIGURED_ARCH),arm64)
    TARGET_ARCH := arm64
else
    TARGET_ARCH := $(CONFIGURED_ARCH)
endif

ifeq ($(CONFIGURED_ARCH), amd64)
FLINES_DS410G_PLATFORM_MODULE = sonic-platform-flines-ds410g-48y8c_$(FLINES_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(FLINES_DS410G_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-flines
$(FLINES_DS410G_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(FLINES_DS410G_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-flines_ds410g_48y8c-r0
SONIC_DPKG_DEBS += $(FLINES_DS410G_PLATFORM_MODULE)
$(eval $(call add_extra_package,$(FLINES_DS410G_PLATFORM_MODULE)))
else ifeq ($(CONFIGURED_ARCH),arm64)
FLINES_DS410H_PLATFORM_MODULE = sonic-platform-flines-ds410h-48y8c_$(FLINES_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(FLINES_DS410H_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-flines
$(FLINES_DS410H_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON) $(PDDF_PLATFORM_MODULE_SYM)
$(FLINES_DS410H_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-flines_ds410h_48y8c-r0
SONIC_DPKG_DEBS += $(FLINES_DS410H_PLATFORM_MODULE)
$(eval $(call add_extra_package,$(FLINES_DS410H_PLATFORM_MODULE)))
else
endif
