# Pegatron Platform modules
FLINES_PLATFORM_MODULE_VERSION = 1.0.1
export FLINES_PLATFORM_MODULE_VERSION
ifeq ($(CONFIGURED_ARCH), amd64)
TARGET_ARCH = x86_64
else
TARGET_ARCH = $(CONFIGURED_ARCH)
endif
FLINES_COMMON_PLATFORM_MODULE = sonic-platform-flines-common_$(FLINES_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(FLINES_COMMON_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-flines
$(FLINES_COMMON_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds410h_48y8c-r0
SONIC_DPKG_DEBS += $(FLINES_COMMON_PLATFORM_MODULE)
$(eval $(call add_extra_package,$(FLINES_COMMON_PLATFORM_MODULE)))

