# Pegatron Platform modules
PEGATRON_PLATFORM_MODULE_VERSION = 1.0.0
export PEGATRON_PLATFORM_MODULE_VERSION
ifeq ($(CONFIGURED_ARCH), amd64)
    TARGET_ARCH = x86_64
else
    TARGET_ARCH = $(CONFIGURED_ARCH)
endif

PEGATRON_FN8032_BNF_PLATFORM_MODULE = sonic-platform-pegatron-fn8032-bnf_$(PEGATRON_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(PEGATRON_FN8032_BNF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pegatron
$(PEGATRON_FN8032_BNF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PEGATRON_FN8032_BNF_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-pegatron_fn8032_bnf-r0
SONIC_DPKG_DEBS += $(PEGATRON_FN8032_BNF_PLATFORM_MODULE)

PEGATRON_FN8031_BNF_PLATFORM_MODULE = sonic-platform-pegatron-fn8031-bnf_$(PEGATRON_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(PEGATRON_FN8031_BNF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pegatron
$(PEGATRON_FN8031_BNF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PEGATRON_FN8031_BNF_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-pegatron_fn8031_bnf-r0
$(eval $(call add_extra_package,$(PEGATRON_FN8032_BNF_PLATFORM_MODULE),$(PEGATRON_FN8031_BNF_PLATFORM_MODULE)))

PEGATRON_FN8030_BNF_PLATFORM_MODULE = sonic-platform-pegatron-fn8030-bnf_$(PEGATRON_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(PEGATRON_FN8030_BNF_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-pegatron
$(PEGATRON_FN8030_BNF_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(PEGATRON_FN8030_BNF_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-pegatron_fn8030_bnf-r0
$(eval $(call add_extra_package,$(PEGATRON_FN8032_BNF_PLATFORM_MODULE),$(PEGATRON_FN8030_BNF_PLATFORM_MODULE)))

PEGATRON_FN8656_BNF_PLATFORM_MODULE = sonic-platform-pegatron-fn8656-bnf_$(PEGATRON_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(PEGATRON_FN8656_BNF_PLATFORM_MODULE)_PLATFORM = $(TARGET_ARCH)-pegatron_fn8656_bnf-r0
$(eval $(call add_extra_package,$(PEGATRON_FN8032_BNF_PLATFORM_MODULE),$(PEGATRON_FN8656_BNF_PLATFORM_MODULE)))
