# Pegatron Platform modules
FLINES_PLATFORM_MODULE_VERSION = 1.0.0
export FLINES_PLATFORM_MODULE_VERSION
ifeq ($(CONFIGURED_ARCH), amd64)
TARGET_ARCH = x86_64
else
TARGET_ARCH = $(CONFIGURED_ARCH)
endif
FLINES_COMMON_PLATFORM_MODULE = sonic-platform-flines-common_$(FLINES_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(FLINES_COMMON_PLATFORM_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-flines
$(FLINES_COMMON_PLATFORM_MODULE)_DEPENDS += $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds410_48y8c-r0
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds610_48c8d-r0
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds730_32d-r0
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds410f_48y8c-r0
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds610f_48c8d-r0
$(FLINES_COMMON_PLATFORM_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds730f_32d-r0
SONIC_DPKG_DEBS += $(FLINES_COMMON_PLATFORM_MODULE)
$(eval $(call add_extra_package,$(FLINES_COMMON_PLATFORM_MODULE)))

FLINES_PLATFORM_PIT_SYSDIAG_MODULE = sonic-platform-flines-pit-sysdiag_$(FLINES_PLATFORM_MODULE_VERSION)_$(CONFIGURED_ARCH).deb
$(FLINES_PLATFORM_PIT_SYSDIAG_MODULE)_SRC_PATH = $(PLATFORM_PATH)/sonic-platform-modules-flines
$(FLINES_PLATFORM_PIT_SYSDIAG_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds610_48c8d-r0
$(FLINES_PLATFORM_PIT_SYSDIAG_MODULE)_PLATFORM += $(TARGET_ARCH)-flines_ds410_48y8c-r0
$(eval $(call add_extra_package,$(FLINES_COMMON_PLATFORM_MODULE),$(FLINES_PLATFORM_PIT_SYSDIAG_MODULE)))
