CLOUNIX_SAI_VERSION=2.2-1.17.1+260319.CU

CLOUNIX_SAI = libsaiclx_$(CLOUNIX_SAI_VERSION)_$(CONFIGURED_ARCH).deb
export clx_sai_deb = $(CLOUNIX_SAI)
$(CLOUNIX_SAI)_PATH = $(PLATFORM_PATH)/
SONIC_COPY_DEBS += $(CLOUNIX_SAI)

CLOUNIX_SAI_DEV = libsaiclx-dev_$(CLOUNIX_SAI_VERSION)_$(CONFIGURED_ARCH).deb
export clx_sai_dev_deb = $(CLOUNIX_SAI_DEV)
$(CLOUNIX_SAI_DEV)_PATH = $(PLATFORM_PATH)/
$(CLOUNIX_SAI_DEV)_DEPENDS += $(CLOUNIX_SAI)
SONIC_COPY_DEBS += $(CLOUNIX_SAI_DEV)
$(eval $(call add_conflict_package,$(CLOUNIX_SAI_DEV),$(LIBSAIVS_DEV)))

CLX_SAI_DBG_DEB ?= no
ifeq ($(CLX_SAI_DBG_DEB), yes)
CLOUNIX_SAI_DBG = libsaiclx-dbg_$(CLOUNIX_SAI_VERSION)_$(CONFIGURED_ARCH).deb
$(CLOUNIX_SAI_DBG)_PATH = $(PLATFORM_PATH)/
$(CLOUNIX_SAI_DBG)_DEPENDS += $(CLOUNIX_SAI)
SONIC_COPY_DEBS += $(CLOUNIX_SAI_DBG)
export clx_sai_dbg_deb = $(CLOUNIX_SAI_DBG)
$(eval $(call add_derived_package,$(CLOUNIX_SAI),$(CLOUNIX_SAI_DBG)))
endif
