# name              lanes                               alias           speed       index   mtu      fec
Ethernet1           2                                   Port1           25000       0       9126     rs
Ethernet2           1                                   Port2           25000       1       9126     rs
Ethernet3           0                                   Port3           25000       2       9126     rs
Ethernet4           6                                   Port4           25000       3       9126     rs
Ethernet5           3                                   Port5           25000       4       9126     rs
Ethernet6           7                                   Port6           25000       5       9126     rs
Ethernet7           4                                   Port7           25000       6       9126     rs
Ethernet8           8                                   Port8           25000       7       9126     rs
Ethernet9           11                                  Port9           25000       8       9126     rs
Ethernet10          5                                   Port10          25000       9       9126     rs
Ethernet11          12                                  Port11          25000       10      9126     rs
Ethernet12          10                                  Port12          25000       11      9126     rs
Ethernet13          13                                  Port13          25000       12      9126     rs
Ethernet14          9                                   Port14          25000       13      9126     rs
Ethernet15          17                                  Port15          25000       14      9126     rs
Ethernet16          14                                  Port16          25000       15      9126     rs
Ethernet17          19                                  Port17          25000       16      9126     rs
Ethernet18          15                                  Port18          25000       17      9126     rs
Ethernet19          21                                  Port19          25000       18      9126     rs
Ethernet20          16                                  Port20          25000       19      9126     rs
Ethernet21          23                                  Port21          25000       20      9126     rs
Ethernet22          18                                  Port22          25000       21      9126     rs
Ethernet23          26                                  Port23          25000       22      9126     rs
Ethernet24          20                                  Port24          25000       23      9126     rs
Ethernet25          28                                  Port25          25000       24      9126     rs
Ethernet26          22                                  Port26          25000       25      9126     rs
Ethernet27          30                                  Port27          25000       26      9126     rs
Ethernet28          25                                  Port28          25000       27      9126     rs
Ethernet29          32                                  Port29          25000       28      9126     rs
Ethernet30          24                                  Port30          25000       29      9126     rs
Ethernet31          34                                  Port31          25000       30      9126     rs
Ethernet32          27                                  Port32          25000       31      9126     rs
Ethernet33          36                                  Port33          25000       32      9126     rs
Ethernet34          29                                  Port34          25000       33      9126     rs
Ethernet35          38                                  Port35          25000       34      9126     rs
Ethernet36          31                                  Port36          25000       35      9126     rs
Ethernet37          39                                  Port37          25000       36      9126     rs
Ethernet38          33                                  Port38          25000       37      9126     rs
Ethernet39          40                                  Port39          25000       38      9126     rs
Ethernet40          35                                  Port40          25000       39      9126     rs
Ethernet41          41                                  Port41          25000       40      9126     rs
Ethernet42          37                                  Port42          25000       41      9126     rs
Ethernet43          43                                  Port43          25000       42      9126     rs
Ethernet44          42                                  Port44          25000       43      9126     rs
Ethernet45          45                                  Port45          25000       44      9126     rs
Ethernet46          44                                  Port46          25000       45      9126     rs
Ethernet47          47                                  Port47          25000       46      9126     rs
Ethernet48          46                                  Port48          25000       47      9126     rs
Ethernet49          55,54,52,53                         Port49          100000      48      9126     rs
Ethernet50          48,51,50,49                         Port50          100000      49      9126     rs
Ethernet51          63,61,62,60                         Port51          100000      50      9126     rs
Ethernet52          56,58,57,59                         Port52          100000      51      9126     rs
Ethernet53          69,68,71,70                         Port53          100000      52      9126     rs
Ethernet54          66,67,64,65                         Port54          100000      53      9126     rs
Ethernet55          76,78,79,77                         Port55          100000      54      9126     rs
Ethernet56          75,72,73,74                         Port56          100000      55      9126     rs
Ethernet57          80                                  Port57          25000       56      9126     rs 
Ethernet58          81                                  port58          25000       57      9126     rs 
